### ISSUE TITLE
Suggestion of features

### ISSUE THREAD

**Issue by tianyu-z** [Fei-Sheng-Wu/UserActivityTracker#7]
Hi Feisheng,

Hope you are doing well and congratulations to your great project.

Do you think it would be helpful or possible to add some "readability" on the loggings . For example, 
- What is the program activated (the name of the process, the title of the window)?
- Which button the user clicked? (e.g. "Apply", "cancel", checked some options). Example below
![image](https://github.com/user-attachments/assets/5eb2e268-a4da-4890-b86b-9e34c233a360)
- 

I am not familar with C# but I personally think adding these features to loggings would even make the project more interesting.

Thank you!

**Comment by Fei-Sheng-Wu** [comment]
The information about the program can be saved in the customizable starting configuration, and while there is no intention at the current moment to add the feature of logging every interaction with every element, a feature was added (Pull Request: https://github.com/Fei-Sheng-Wu/UserActivityTracker/pull/13) where one can programmatically add a custom string message to the recording that can be outputted to the logs during the playing.

Thank you for your feedback.
